# Generated by Django 4.2.1 on 2026-05-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sent_by',
        ),
    ]
